### ISSUE TITLE
contact us is not working 

### ISSUE THREAD

**Issue by Isha1233** [Akshatchaube01/TimeWarp#105]
**Describe the bug**
on clicking contact us button showing a pop up something went wrong

**To Reproduce**
1. Go to 'contact us'
2. fill form 'contact us' 
3. Scroll down to 'contact us' button

**Expected behavior**
on clicking the contact us button with send message successfully.

**Screenshots**

![WhatsApp Image 2024-05-23 at 00 33 36](https://github.com/Akshatchaube01/TimeWarp/assets/120541874/fda7c187-69ca-49e6-8b89-1debb4562ddb)

**Comment by Isha1233** [comment]
@Akshatchaube01 kindly assign this task to me I will fix it

**Comment by Neh2005** [comment]
Hi,
Seems like still the issue is not solved. I will be able to fix it. Can I also work on this issue under Gssoc?

**Comment by Isha1233** [comment]
@Neh2005 check code properly owner need to add service ID and template ID there then this will work fine as add our own db link to acess backend.
