### ISSUE TITLE
API Reference link doesn't redirect to its designated website

### ISSUE THREAD

**Issue by Dyuksha27** [Akshatchaube01/TimeWarp#107]
**Describe the bug**
Under the demo section, API Reference link doesn't take you to its designated website; instead, google opens up.

**To Reproduce**
1. Go to 'Demo Section'.
2. Click on 'API Reference'
3. Google appears instead of any website

**Expected behavior**
On clicking the API Reference link, it should point to its designated website.

**Screenshots**

<img width="451" alt="image" src="https://github.com/Akshatchaube01/TimeWarp/assets/143547081/27a2e940-0e5b-48a1-b2b5-9c004b0357f9">

<img width="451" alt="image" src="https://github.com/Akshatchaube01/TimeWarp/assets/143547081/5f0ea4ec-06f6-4b23-ab2c-ec8922192bed">

**Comment by Dyuksha27** [comment]
@Akshatchaube01 kindly assign this issue to me

**Comment by manishprasad9156** [comment]
@Akshatchaube01 Kindly assign this issue to me. I have the experience to solve this isuue.

**Comment by Akshatchaube01** [comment]
Will open this issue later
