### ISSUE TITLE
Content in the navbar not clearly visible 

### ISSUE THREAD

**Issue by Dyuksha27** [Akshatchaube01/TimeWarp#109]
**Describe the bug**
Content in the navbar is not clearly visible.

**To Reproduce**
1. Go to 'Demo section'
3. Scroll down till the end of page
4. You'll observe that the content in the navbar is not clearly visible

**Expected behavior**
Content of the navbar will be clearly visible.

**Screenshots**

<img width="451" alt="image" src="https://github.com/Akshatchaube01/TimeWarp/assets/143547081/7cdf89d2-0973-4c77-8bf4-df30c71a2b33">

**Comment by Dyuksha27** [comment]
@Akshatchaube01 kindly assign me this issue as well

**Comment by Akshatchaube01** [comment]
How do you plan on solving this issue ?

**Comment by Dyuksha27** [comment]
To resolve this, I'll change the color of the content in the navbar. The background is dark at the top of the page in the demo section and lightens as we scroll down which reduces visibility of the text. Therefore, I'll adjust the content color to ensure visibility in both light and dark backgrounds.

**Comment by Harsha19-08** [comment]
@Akshatchaube01  Could you please assign me this problem? The navigation bar is now clearly visible, but the hover effect is not ideal, and the light and dark mode effects underneath the bar don't have any CSS properties. I'll repair that by making the navigation bar responsive and stylish.

**Comment by Harsha19-08** [comment]
Hi @Akshatchaube01  ihave fixed both the footer and nav bar can u check this and assign this to me under level 1 or level2 
![image](https://github.com/Akshatchaube01/TimeWarp/assets/127961910/c3a96c51-f8a6-4ed6-b0ef-ce609de4584a)
![image](https://github.com/Akshatchaube01/TimeWarp/assets/127961910/6116d143-aa89-4e86-9a53-dbef27b38483)


added some cool animations to the nav bar and the footer can u preview this images for it

**Comment by Akshatchaube01** [comment]
@Harsha19-08 please raise a new issue

**Comment by Akshatchaube01** [comment]
This issue has been fixed
