### ISSUE TITLE
Create Proper Readm.MD

### ISSUE THREAD

**Issue by Harshu467** [Akshatchaube01/TimeWarp#11]
As of now ReadMe .MD is not proper , there should be proper steps like how to clone , screenshots.
I will make proper Readme file

**Comment by Harshu467** [comment]
My self Harsh Upadhye , I have participated in GSOC 23 last year, I have good experience of working on open source projects. Please Assign this to me

**Comment by Akshatchaube01** [comment]
Sure go ahead
