### ISSUE TITLE
The models page cards are one in a row 

### ISSUE THREAD

**Issue by Rohitha-pudu** [Akshatchaube01/TimeWarp#118]
aligning more cards in a row

**Comment by Akshatchaube01** [comment]
can you elaborate ?

**Comment by Rohitha-pudu** [comment]
![image](https://github.com/Akshatchaube01/TimeWarp/assets/116823590/c15259cb-e8f7-4829-abee-ef602fdb91f9)
in desktop there is only one model per row,making them to 2/3

**Comment by Akshatchaube01** [comment]
How about 3 cards per row with the middle one being the largest , what do you think ?

**Comment by Rohitha-pudu** [comment]
> How about 3 cards per row with the middle one being the largest , what do you think ?

looks good

**Comment by Rohitha-pudu** [comment]
> > How about 3 cards per row with the middle one being the largest , what do you think ?
> 
> looks good

can i just do 3 cards in a row ,the middle one being the largest is having some issues
