### ISSUE TITLE
Timeline Slider

### ISSUE THREAD

**Issue by Rohitha-pudu** [Akshatchaube01/TimeWarp#119]
Including a timeline slider that allows users to adjust the time period they are viewing dynamically. This feature enables users to seamlessly transition between different historical eras and compare changes over time.

**Comment by Rohitha-pudu** [comment]
where should i keep the timeline slider?

**Comment by Akshatchaube01** [comment]
Below the models

**Comment by Rohitha-pudu** [comment]
> Below the models

ok
