### ISSUE TITLE
Footer Creation

### ISSUE THREAD

**Issue by Harshu467** [Akshatchaube01/TimeWarp#12]
As of now there is no Footer , we need to create proper footer to add proper links and socials in Footer

**Comment by Harshu467** [comment]
My self Harsh Upadhye , I have participated in GSOC 23 last year, I have good experience of working on open source projects. Please Assign this to me

**Comment by Akshatchaube01** [comment]
Please proceed, and I will consider merging the content only if it meets the desired standards of quality. Feel free to request any necessary social media handles or contact information directly in this communication

**Comment by rishabh-bijalwan12** [comment]
is this work is done or not

**Comment by Artuiro-23** [comment]
I can work on this task. Kindly assign me this task.
Thankyou.
