### ISSUE TITLE
Adding an attractive footer in site

### ISSUE THREAD

**Issue by Isha1233** [Akshatchaube01/TimeWarp#127]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Isha1233** [comment]
@Akshatchaube01 kindly assign this task to me I will do it efficiently

**Comment by Akshatchaube01** [comment]
This issue has been solved
