### ISSUE TITLE
Feature of auto Commenting on new issue creation

### ISSUE THREAD

**Issue by suhanipaliwal** [Akshatchaube01/TimeWarp#129]
This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

**Comment by Akshatchaube01** [comment]
Not looking for this right now.
