### ISSUE TITLE
Mobile Responsiveness for Homepage 

### ISSUE THREAD

**Issue by Akshatchaube01** [Akshatchaube01/TimeWarp#14]
Give mobile friendly responsiveness to the home page, with the navbar opening on clicking a button
An example  :

<img width="485" alt="Screenshot_1" src="https://github.com/Akshatchaube01/TimeWarp/assets/92796050/331acdb4-7fed-4683-8d29-8567e90c6bcd">

No need to change the colour theme (keep it same as the Timewarp website)

**Comment by rishabh-bijalwan12** [comment]
we can add tailwind css so that navbar will be responsive

**Comment by rishabh-bijalwan12** [comment]
you can assign it to me i can do it

**Comment by rishabh-bijalwan12** [comment]
working on it
