### ISSUE TITLE
Add Theme Button (Dark/Light)

### ISSUE THREAD

**Issue by ParthNakum21** [Akshatchaube01/TimeWarp#141]
Adding a theme button that changes the theme of the website from light to dark or dark to light can enhance the user experience. The user can change the themes according to their preference. 

Could you please assign this task to me under GSSoC with appropriate level?

**Comment by ParthNakum21** [comment]
Thanks! Working on it. 
Could you please assign the level as well?

**Comment by Akshatchaube01** [comment]
Will add the level after merge
