### ISSUE TITLE
Stop Autoplay of video

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Akshatchaube01/TimeWarp#146]
**Is your feature request related to a problem? Please describe.**
When i go to the demo section then after scrolling the youtube video automatically started playing and their is some user who didn't like things to play on their device automatically when they are sitting in the silent environement .

**Describe the solution you'd like**
I want to remove the autoplay of the video 

![Screenshot 2024-05-26 123840](https://github.com/Akshatchaube01/TimeWarp/assets/118350936/03393df6-02a2-43d4-9c95-a31b2a6b4b62)

**Comment by AMS003010** [comment]
Hello @Akshatchaube01 🤗

Would be great if I could work on this issue. From what I can figure, it seems to be a simple fix of removing the autoplay in  the iframe tag in the [DemoSection.jsx](https://github.com/Akshatchaube01/TimeWarp/blob/main/src/components/DemoSection.jsx)

**Comment by Akshatchaube01** [comment]
@AMS003010 hey, this issue has already been assigned !
