### ISSUE TITLE
The theme got changed 

### ISSUE THREAD

**Issue by Rohitha-pudu** [Akshatchaube01/TimeWarp#151]
There is no toggle theme button  #144  and everything is changed to light theme which is missing some elements.

**Comment by Akshatchaube01** [comment]
Can you explain further with screenshots

**Comment by Rohitha-pudu** [comment]
> Can you explain further with screenshots

there is no toggle button,
![image](https://github.com/Akshatchaube01/TimeWarp/assets/116823590/b54ba7e3-e048-4b53-89dd-6e96c2cd600e)

**Comment by Akshatchaube01** [comment]
<img width="953" alt="Screenshot_1" src="https://github.com/Akshatchaube01/TimeWarp/assets/92796050/449fef4f-c2fa-4653-8990-d8f7ac8282cc">
The toggle button seems to be there...

**Comment by Rohitha-pudu** [comment]
Its not present in the deployed link!  may be i am wrong,sorry

**Comment by Akshatchaube01** [comment]
No problem, try disabling some extensions on your browser
