### ISSUE TITLE
Floating Nav Bar

### ISSUE THREAD

**Issue by Rohitha-pudu** [Akshatchaube01/TimeWarp#159]

**Comment by Rohitha-pudu** [comment]
![image](https://github.com/Akshatchaube01/TimeWarp/assets/116823590/a0de68d6-87ec-4301-b557-daaf3b82c210)
is it okay? @Akshatchaube01

**Comment by Harsha19-08** [comment]
@Akshatchaube01  can u assign me this issue

**Comment by Akshatchaube01** [comment]
@Harsha19-08 this issue has already been assigned.

**Comment by Harsha19-08** [comment]
@Akshatchaube01 okay but the pr was not made so i can fix that too if the assigned person is not on the flow to go with that
