### ISSUE TITLE
[UI Enhancement] : Implement typography, modern background and Tailwind Dependency

### ISSUE THREAD

**Issue by kshavp** [Akshatchaube01/TimeWarp#16]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem, but we can enhance the overall UI a little bit.

**Describe the solution you'd like**
I'd like to add tailwind dependency, additional typography and better background.

**Describe alternatives you've considered**
N/A

**Additional context**

What problem is this feature trying to solve?
Enhancement of UI

How do we know when the feature is complete?
I'll ping a PR as soon as i complete the UI enhancement.

**Comment by Akshatchaube01** [comment]
Great ! You can add the tailwind dependency and additional typography. Background work has already been taken.

**Comment by manpreet244** [comment]
I wanna work on the UI enhancement,please assign me this issue under gssoc24

**Comment by Akshatchaube01** [comment]
@manpreet244 you can raise an issue of your own, and start working on it if it is assigned to you.
