### ISSUE TITLE
Adding dynamic background in models and contact us and changing the cursor according to background

### ISSUE THREAD

**Issue by happyrao78** [Akshatchaube01/TimeWarp#163]
Adding dynamic background
Changing cursor according to dynamic background.

**Comment by happyrao78** [comment]
@Akshatchaube01 Kindly assign the labels.

**Comment by happyrao78** [comment]
@Akshatchaube01 please assign me the level's label so  that I can start with the project.

**Comment by happyrao78** [comment]
@Akshatchaube01 Levels??

**Comment by Akshatchaube01** [comment]
I would like you to make separate issues for all these tasks, or I can assign a level 3 for doing all these.

**Comment by happyrao78** [comment]
@Akshatchaube01 You can assign me level 3 for this.
