### ISSUE TITLE
Navbar animation on Mobile devices

### ISSUE THREAD

**Issue by Sypher0Dronzer** [Akshatchaube01/TimeWarp#164]
**Is your feature request related to a problem? Please describe.**
For mobile devices, the navbar dropdown comes all of a sudden.

**Describe the solution you'd like**
I want to add a smooth transition for the dropdown of the navbar for a smooth user experience

What problem is this feature trying to solve?

How do we know when the feature is complete?

https://github.com/Akshatchaube01/TimeWarp/assets/83546205/b98c48f5-d1f4-4357-b8c0-707c43efbf9d

please assign this issue to me

**Comment by Akshatchaube01** [comment]
Can you please pull the recent changes and then commit
