### ISSUE TITLE
Issue with the light and dark mode

### ISSUE THREAD

**Issue by aritra-sarkar-42** [Akshatchaube01/TimeWarp#165]
**Describe the bug**
in the dark mode every thing is fine but in light mode the animations on the about us page are not visible properly and the text on the contact us page is not visible,

**To Reproduce**
just turn on the light mode and see the contact us page and the about us page

**Expected behavior**
everything should be properly visible even  when the modes are toggled in beyween

**Screenshots**

![image](https://github.com/Akshatchaube01/TimeWarp/assets/144362932/36ae6644-cf51-4dc9-a894-61a81ed0cead)

Please assign this issue to me @Akshatchaube01

**Comment by Harsha19-08** [comment]
@Akshatchaube01  can u assign me this issue u can consider the both the requests and pick the best out of both the pull requests

**Comment by Akshatchaube01** [comment]
This issue has been fixed
