### ISSUE TITLE
Problem with Footer

### ISSUE THREAD

**Issue by aritra-sarkar-42** [Akshatchaube01/TimeWarp#166]
**Describe the bug**
The alignment of the contents is improper.

**To Reproduce**
check the footer in any section - About Us/DemoSection /Models

**Expected behavior**
It should be properly alligned to be visually pleasing.

**Screenshots**
![image](https://github.com/Akshatchaube01/TimeWarp/assets/144362932/e923dd2c-7940-419e-acde-6ca0547a8be0)

Please assign it to me @Akshatchaube01

**Comment by Harsha19-08** [comment]
Hi @Akshatchaube01  ihave fixed both the footer and nav bar can u check this and assign this to me under level 1 or level2 
![image](https://github.com/Akshatchaube01/TimeWarp/assets/127961910/c3a96c51-f8a6-4ed6-b0ef-ce609de4584a)
![image](https://github.com/Akshatchaube01/TimeWarp/assets/127961910/6116d143-aa89-4e86-9a53-dbef27b38483)


added some cool animations to the nav bar and the footer can u preview this images for it

**Comment by Akshatchaube01** [comment]
Issue has been fixed
