### ISSUE TITLE
Changing landing page font of [Timewarp]

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Akshatchaube01/TimeWarp#169]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/Akshatchaube01/TimeWarp/assets/125277258/59be40ce-d206-4800-9c12-ad3fc5a210cb)

**Additional context**

**Comment by RamakrushnaBiswal** [comment]
@Akshatchaube01 i want to work upon it can you assign it to me under GSSOC 24

**Comment by Akshatchaube01** [comment]
We are not looking for this right now. You can try working on other issues. Thankyou
