### ISSUE TITLE
[Feature]: Frost glass design on Our team Cards

### ISSUE THREAD

**Issue by Sypher0Dronzer** [Akshatchaube01/TimeWarp#172]
**Is your feature request related to a problem? Please describe.**
The design of cards in the Our Team section can be improved to make it look even cooler with frost glass

![image](https://github.com/Akshatchaube01/TimeWarp/assets/83546205/3ff64db1-e345-4723-9854-76f54e157d45)

**Describe the solution you'd like**
I wish to add a frost glass styles theme to the cards of the Our Teams section

**Describe alternatives you've considered**
I wish to change the tailwind properties of the cards

**Additional context**

What problem is this feature trying to solve?
improving the UI of the website

How do we know when the feature is complete?
Changes will be made and shown through screenshots in the pull request

please assign this issue to me

**Comment by Sypher0Dronzer** [comment]
https://github.com/Akshatchaube01/TimeWarp/assets/83546205/9257d126-8fa7-46ed-ad19-a9df27ef73fd

How does this look ?

**Comment by Akshatchaube01** [comment]
Be sure to pull the recent changes before you make a PR
