### ISSUE TITLE
[Bug]: Light theme Text not visible in Contact page

### ISSUE THREAD

**Issue by Sypher0Dronzer** [Akshatchaube01/TimeWarp#173]
**Describe the bug**
In light theme of contact page the texts arent visible 

**To Reproduce**
1. Go to 'contact.html'
2. Click on 'classname'
3. Scroll down to 'The part which contains the error'

**Expected behavior**
The header such as Contact Us along with the input decriptions like your Name, your email should be visible

**Screenshots**
![image](https://github.com/Akshatchaube01/TimeWarp/assets/83546205/786bd27d-9a8f-4f10-9639-76ee35a5ac75)

![image](https://github.com/Akshatchaube01/TimeWarp/assets/83546205/6b9d10cf-1e47-42e4-815d-714c3d2de7eb)

please assign this issue to me 

**Additional context**

**Comment by Akshatchaube01** [comment]
This issue has already been raised.
