### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by shreyyq** [Akshatchaube01/TimeWarp#175]
***Issue:*** The website is not fully responsive on all mobile devices.

***Suggestion:*** Implement responsive design techniques using CSS media queries to ensure the website looks good on all screen sizes.

***Benefits:*** Improved user experience on mobile devices, increased mobile traffic.

please assign this issue to me under gssoc

**Comment by Akshatchaube01** [comment]
Can you please share some screenshots to show the problem ?
