### ISSUE TITLE
Major Update in Styling of Footer

### ISSUE THREAD

**Issue by say-het** [Akshatchaube01/TimeWarp#177]
**Describe the bug**
The footer's design was quite off compare to the design of the rest of the website.

So I have
 - Updated the stylings
 - Updated the background 
 - Given glass effect to the background that looks incredible 
 - I have made some changes in the alignment of the stuff

Hey @Akshatchaube01 I have already done this task. Please assign me this issue so that I can raise a PR.

Little About Me: I am an experienced Contributor as I have successfully completed Hacktoberfest-2020 and Hacktoberfest-2023

**Comment by Akshatchaube01** [comment]
can you please give a screenshot of your work

**Comment by say-het** [comment]
Sure, Here it is!

![image](https://github.com/Akshatchaube01/TimeWarp/assets/71073587/c4f2e717-898b-4742-ac00-5ae251b9fa6c)

**Comment by Akshatchaube01** [comment]
Looks good ! please make a PR and be sure to pull all the recent changes
