### ISSUE TITLE
Animated feature to contact us page

### ISSUE THREAD

**Issue by Harsha19-08** [Akshatchaube01/TimeWarp#182]
**Is your feature request related to a problem? Please describe.**
Fixing the contact us page issue when it is dark mode and light mode and adding total animation for the entire animation page 

**Describe the solution you'd like**
adding animations thorough css and other react libraries like accentricity and  adding time related animations to the page
Expected behavior
everything should be properly visible even when the modes are toggled in between

Fixing this 
![image](https://github.com/Akshatchaube01/TimeWarp/assets/127961910/a90cd4ae-1e96-4b7b-ae96-548f16a6a23a)

my previous works on contact forms are 
![image](https://github.com/Akshatchaube01/TimeWarp/assets/127961910/5bc07414-13ce-4617-9a02-bd587dd8274f)

I can animate or fix this in this way
![image](https://github.com/Akshatchaube01/TimeWarp/assets/127961910/e9f88672-b39f-41a0-a513-2b0462257174)
 and also by adding time related designs to  it 
 @Akshatchaube01 can u assign me this issue  to work on this

**Comment by Akshatchaube01** [comment]
We don't want to change the page at all, only fix the font part, the font color must change when we toggle from dark mode to light mode so that it is visible. That is all

**Comment by Harsha19-08** [comment]
@Akshatchaube01 Ok cool can u assign me this issue so that i can work on it
