### ISSUE TITLE
Fixing Navbar and Footer 

### ISSUE THREAD

**Issue by Harsha19-08** [Akshatchaube01/TimeWarp#183]
**Describe the bug**
1)There is and issue of navbar and the dark/light toggle colour and the nav elements are not good looking due to text decoration
2) fixing the footer and animating the footer according to the colours used in TimeWrap
**To Reproduce**
1)Go to 'Demo section'
2)You can observe the underline decoration to it and there is no hover effect to 
3)while u scroll down the footer is not given the colour according the basic colours of the TimeWrap
![image](https://github.com/Akshatchaube01/TimeWarp/assets/127961910/015d5e93-2347-49af-9e02-ae15e8a28038)
![image](https://github.com/Akshatchaube01/TimeWarp/assets/127961910/b665443d-bf72-480d-9eac-a16e9208c01a)

**Expected behavior**
A matchable and cool colours and effects to the footer and making the visibility of nav bars toggle effect

**Screenshots**
![image](https://github.com/Akshatchaube01/TimeWarp/assets/127961910/3aa58cb7-cf52-4d6b-93cd-d94b10678934)

![image](https://github.com/Akshatchaube01/TimeWarp/assets/127961910/6eb283d9-88ba-402a-a8dc-aff9f751ca6e)

**Additional context**
@Akshatchaube01  can u assign me this issue under GSSOC2024 level 1 or level2

**Comment by Harsha19-08** [comment]
@Akshatchaube01 can u check the pr

**Comment by Akshatchaube01** [comment]
The deployment failed, try again 
Also, I checked the preview, do not change the navbar - the hover effect doesn't suit it well. And I want you to fix the footer only such that it is light blue(the one in preview) only during the light mode, otherwise I want it how it is. Please follow this and I'll merge your PR.

**Comment by Harsha19-08** [comment]
@Akshatchaube01  okok i will definitely doo that..
