### ISSUE TITLE
Two different Navbars

### ISSUE THREAD

**Issue by kshavp** [Akshatchaube01/TimeWarp#19]
The App.jsx and Home.jsx contain separate navbars as shown in the attachment, suggest a fix to work upon.

 **App.jsx**
![image](https://github.com/Akshatchaube01/TimeWarp/assets/95236968/3e379b2c-d44e-469b-ad7f-0599170238c2)

**Home.jsx**
![image](https://github.com/Akshatchaube01/TimeWarp/assets/95236968/168cd657-8e80-4210-b73d-226cc052bdfb)

**Comment by IshaanMinocha** [comment]
ill solve this issue if you want and have only one navbar which will be defined from app

**Comment by Akshatchaube01** [comment]
Sure, I am assigning it to you as well

**Comment by IshaanMinocha** [comment]
sent a pr, also added an extra feature. check it out @Akshatchaube01 and close this issue after merging
