### ISSUE TITLE
Home page updation.

### ISSUE THREAD

**Issue by happyrao78** [Akshatchaube01/TimeWarp#190]
Updating the design and effect of home page.

**Comment by Akshatchaube01** [comment]
Can you elaborate the issue more ?

**Comment by happyrao78** [comment]
Adding more interactive background. 
Something like this below which as fireflies in background and a static background.
![Screenshot 2024-06-02 103806](https://github.com/Akshatchaube01/TimeWarp/assets/138770813/1fc86d31-9dcb-424d-9572-2b6e67d766f8)

**Comment by Akshatchaube01** [comment]
Not looking for this right now
