### ISSUE TITLE
Add little but yet important information about team members on each of their cards 

### ISSUE THREAD

**Issue by gungunjain15** [Akshatchaube01/TimeWarp#191]
on hovering over each card of the team member in about us section we can display their name, designation, their domains and contact info like github and linkedin to make their profile more visible.
@Akshatchaube01 Can you please assign this issue to me as my first contribution in gssoc .
Thanks

For reference : - 
![image](https://github.com/Akshatchaube01/TimeWarp/assets/125124845/97e1678f-2656-4beb-8b76-e721e9e8d433)

**Comment by Akshatchaube01** [comment]
This issue has already been raised
