### ISSUE TITLE
Scroll to top button with Scroll Progress

### ISSUE THREAD

**Issue by gungunjain15** [Akshatchaube01/TimeWarp#193]
For the user to directly access the top section after reaching the footer or any in between section saves a lot of time and avoid to scrolling back to each one of them above it. This button is featured with an icon ,bright color and scroll progress on border, not to clutter up the feature with extra details.
@Akshatchaube01 Sir can you please assign this issue to me to add the feature in your website to make it more feasible.

**Comment by Akshatchaube01** [comment]
This issue has already been raised and is being worked on.
