### ISSUE TITLE
Social Links

### ISSUE THREAD

**Issue by say-het** [Akshatchaube01/TimeWarp#208]
**Describe the bug**

  - Hey @Akshatchaube01 I noticed the links to the socials in the footer has some issue.
  - Twitter and Instagram links are just their website links 
  - It lacks personalized links
  - If you want to add it, I can add it just give me the socials that you might put there.
  - If not than It should be removed because it looks unprofessional to put just website links there.

**Comment by Akshatchaube01** [comment]
Not looking for this right now
