### ISSUE TITLE
Changing the color of the floating line to improve visibility & improving button.

### ISSUE THREAD

**Issue by IbrahimDev00** [Akshatchaube01/TimeWarp#213]
Description : When hovering over the description, the effect makes the text low in visibility and difficult to read. The "know more" button is barely visible as it merges in with the background.

Can be seen in : The landing page.

Expected behaviour : Having better color contrast to enhance visibility.

Video: 

https://github.com/Akshatchaube01/TimeWarp/assets/147825977/e1f0ea52-7aeb-47e2-895e-ee651d3515fd

Steps to improve : Change the color to improve visibility , try using colors with more contrast, or trying to blur the background a little by increasing opacity.

Please assign this to me under GSSoC'24.

**Comment by Akshatchaube01** [comment]
We're not looking for this change right now
