### ISSUE TITLE
Enhance Footer

### ISSUE THREAD

**Issue by Amruta7203** [Akshatchaube01/TimeWarp#219]
**Is your feature request related to a problem? Please describe.**
The current can be enhanced for a better user experience and engagement.

**Describe the solution you'd like**
Having a proper alignment of components and contact info (including the icons and text) 

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Akshatchaube01** [comment]
We are not looking for this right now
