### ISSUE TITLE
More info in Read me file

### ISSUE THREAD

**Issue by Varda003** [Akshatchaube01/TimeWarp#22]
How to contribute to this repository is not mentioned as well some extra details about the project can also be added

**Comment by Varda003** [comment]
Please assign this issue to me I am well experienced in creating documentation

**Comment by Varda003** [comment]
@Akshatchaube01  Please add GSSOC'24 label and Level 1 , 2 ,3 as well according to you or else my Pr won't be counted

**Comment by Akshatchaube01** [comment]
#11 the issue is already being worked on

**Comment by Akshatchaube01** [comment]
Since #11  is not being worked upon, you can start working on this issue.

**Comment by Varda003** [comment]
But didn't you already assigned it to someone sir are sure I can work because I will complete it today itself. @Akshatchaube01

**Comment by Akshatchaube01** [comment]
yeah, you can start working on it

**Comment by Varda003** [comment]
Sir @Akshatchaube01 Its completely up to you what level you consider this problem but just asking you to consider level 2 label cause their nothing in the read me file and I have to study you project completely to understand and add all the things, it would be great if you could change it to level 2 please.

**Comment by Varda003** [comment]
Sir one info is needed do we need to install some other packages to work on this project so any other  person will know I will add it into installation part

**Comment by Akshatchaube01** [comment]
currently not needed

**Comment by Varda003** [comment]
sir #22 is still open so where is my contribution counted
