### ISSUE TITLE
Alignment of text at homepage

### ISSUE THREAD

**Issue by happyrao78** [Akshatchaube01/TimeWarp#220]
Aligning the homepage timewarp title and its heading to the right so that it looks more attractive and readable.
![Screenshot 2024-06-04 131245](https://github.com/Akshatchaube01/TimeWarp/assets/138770813/3657725d-babf-4c95-874a-93e7e0e3ac94)

**Comment by happyrao78** [comment]
@Akshatchaube01 kindly review the issue.

**Comment by Akshatchaube01** [comment]
We are not looking for this right now
