### ISSUE TITLE
Improving the on hover effect.

### ISSUE THREAD

**Issue by happyrao78** [Akshatchaube01/TimeWarp#221]
Improving the on hover effect of subheading present in homepage as it is not  much visible when hovered.
![Screenshot 2024-06-04 131256](https://github.com/Akshatchaube01/TimeWarp/assets/138770813/b06975c3-604e-4b61-b2a0-000f644aff7a)

**Comment by happyrao78** [comment]
@Akshatchaube01 Kindly review issue.

**Comment by Akshatchaube01** [comment]
We are not looking for this right now
