### ISSUE TITLE
[Bug] : Due to Background hero button is not proper visible

### ISSUE THREAD

**Issue by dhruv8433** [Akshatchaube01/TimeWarp#228]
**Describe the bug**
@Akshatchaube01 

check this out,
on hero section, the background and button are almost same and quite not to proper visible

**To Reproduce**
1. Go to home page

**Expected behavior**
 we can change button color 

**Screenshots**
![image](https://github.com/Akshatchaube01/TimeWarp/assets/114583978/4f708620-f939-467c-90e3-6bf534262d77)

**Additional context**

**Comment by Akshatchaube01** [comment]
We are not looking for this right now
