### ISSUE TITLE
Enhancing the contact us page UI

### ISSUE THREAD

**Issue by anwesha2002** [Akshatchaube01/TimeWarp#23]
**Is your feature request related to a problem? Please describe.**
I would like to enhance the UI of the contact us page

**Describe the solution you'd like**
I would like to make the UI better in Contact us page by adding a form of "get in touch" and by changing some UI

**Describe alternatives you've considered**
@Akshatchaube01 
I am a GSSOC'24 contributor. I would like to work on this feature . Please assign this to me.

**Additional context**
![Screenshot 2024-05-11 134426](https://github.com/Akshatchaube01/TimeWarp/assets/116761608/ab29f6ce-fb2d-482a-a9eb-4ca1124aa724)

What problem is this feature trying to solve?
UI enhancement, React 

How do we know when the feature is complete?
navigating to contact us page

**Comment by Artuiro-23** [comment]
I want to work on this issue. Kindly assign me this task.
Thankyou.
