### ISSUE TITLE
[Feat] : We can create Privacy Page

### ISSUE THREAD

**Issue by dhruv8433** [Akshatchaube01/TimeWarp#235]
**Is your feature request related to a problem? Please describe.**

@Akshatchaube01 
we can create privacy page for this web

**Describe the solution you'd like**
- we can design privacy policy for thiis website
- when user visit `/privacy-policy` they got access of this page

How do we know when the feature is complete?

**Comment by dhruv8433** [comment]
Thank you @Akshatchaube01

**Comment by dhruv8433** [comment]
@Akshatchaube01 

can i get level 3 ??
i also design it responsive and beautiful

**Comment by Akshatchaube01** [comment]
Alright, make sure to keep a good theme for the entire page

**Comment by dhruv8433** [comment]
@Akshatchaube01 

Thank you
