### ISSUE TITLE
[ Enhancement ] : Fixes to improve readability

### ISSUE THREAD

**Issue by kshavp** [Akshatchaube01/TimeWarp#237]
**Describe the bug**
As shown in the attached media, in the dark mode the text appears to be camouflaging with the provided background.  

**Expected behavior**
The Text color and background should contrast to have a better readability.

**Screenshots**
![image](https://github.com/Akshatchaube01/TimeWarp/assets/95236968/b1a88d95-52a4-4f62-9043-462730f97e11)
![image](https://github.com/Akshatchaube01/TimeWarp/assets/95236968/0ceee472-5f9a-4587-a8fa-3ecaa27780a5)

@Akshatchaube01 I'd raise the PR by today.

**Comment by Akshatchaube01** [comment]
We are not looking for this right now
