### ISSUE TITLE
[Feat] : We can add Terms Page

### ISSUE THREAD

**Issue by dhruv8433** [Akshatchaube01/TimeWarp#239]
**Is your feature request related to a problem? Please describe.**
@Akshatchaube01 

we can add new route `/terms-and-conditions`
we can add beautifully designed Terms page
it's also important part of any website

**Describe the solution you'd like**
- we can create new page for terms and conditions

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?
- when we visit `/terms-and-condition` route we can see that page

**Comment by Akshatchaube01** [comment]
Similar to the last PR, do not add it in the navigation

**Comment by dhruv8433** [comment]
@Akshatchaube01 Thank you :)
