### ISSUE TITLE
Contact Us screen  on the web : Fully Functional

### ISSUE THREAD

**Issue by aritra-sarkar-42** [Akshatchaube01/TimeWarp#24]
**Is your feature request related to a problem? Please describe.**

Having a contact me section with an inbuilt fully functional setup is a massive bonus point. Many users actually would love to have a functional contact form. It would be less time consuming and on the go.

**Describe the solution you'd like**

In the contact us section I can create e separate pop-up form where the user will be able to send a message directly to the assigned mailing address all within the application.

**Describe alternatives you've considered**

If we don't do a pop-up one I can make  a simplified minimalistic contact us form where it will be fully functional and the users will be able to directly message through the application. 

**Additional context**

Having a contact me section with an inbuilt fully functional setup is a massive bonus point. Many users actually would love to have a functional contact form. It would be less time consuming and on the go.

![image](https://github.com/Akshatchaube01/TimeWarp/assets/144362932/2a7ca4d7-1ff8-4501-abe8-de263224a312)

this is an example of the idea I am talking about and this is something I have previously implemented

What problem is this feature trying to solve?

Communication would be a lot simpler and would fetch a lot more responses as users won't have to burn those extra calories to go to the mailing app and would be within the application.

How do we know when the feature is complete?
It will take 2-4 days to implement moreover I will inform the mentor of this project about the same through email.

I would like to implement this -the backend as well as the UI .Please assign this to me @Akshatchaube01 .

**Comment by Akshatchaube01** [comment]
Sure go ahead !

**Comment by Akshatchaube01** [comment]
@aritra-sarkar-42 Hey, can you make the PR again with the updated code.

**Comment by aritra-sarkar-42** [comment]
yes sure

**Comment by aritra-sarkar-42** [comment]
@Akshatchaube01 Sir I have created the pull request with the updated code
