### ISSUE TITLE
[Bug] : Missing Footer in Contact us section

### ISSUE THREAD

**Issue by dhruv8433** [Akshatchaube01/TimeWarp#249]
**Describe the bug**

@Akshatchaube01 
- missing footer section in contact us
- we can add it 

**To Reproduce**
1. Go to '/contactus' section

**Expected behavior**

**Screenshots**

![image](https://github.com/Akshatchaube01/TimeWarp/assets/114583978/51d4d875-9998-4630-ba73-c6ea17331809)

**Additional context**

**Comment by Akshatchaube01** [comment]
We are not looking for this change right now
