### ISSUE TITLE
Adding Audiowide font to the home page. 

### ISSUE THREAD

**Issue by GayathriPCh** [Akshatchaube01/TimeWarp#266]
The HomePage already looks cool, but would cooler with a futuristic font
Using AudioWide would look awesome, is what i think.

Original: 
![image](https://github.com/Akshatchaube01/TimeWarp/assets/132088009/2de1a9cb-bc4a-4d4e-a11f-2486087804c3)
With Audiowide: 
![image](https://github.com/Akshatchaube01/TimeWarp/assets/132088009/ad45d5ac-cb72-41c0-87a3-ed7025199f69)

I would like to contribute by adding this. Under GSSOC 24. Thanks for considering.

**Comment by Akshatchaube01** [comment]
We re not looking for this change right now
