### ISSUE TITLE
[Feat] : Add Code of Conduct page 

### ISSUE THREAD

**Issue by dhruv8433** [Akshatchaube01/TimeWarp#268]
**Is your feature request related to a problem? Please describe.**

@Akshatchaube01 

we can add code of conduct page
something like this

![image](https://github.com/Akshatchaube01/TimeWarp/assets/114583978/ca580a5e-eafd-461b-ab05-edc7553de1ff)

we can customize and design as per our theme

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Akshatchaube01** [comment]
We are not looking for this right now
