### ISSUE TITLE
[Feat] : Design Cookie policy page

### ISSUE THREAD

**Issue by dhruv8433** [Akshatchaube01/TimeWarp#269]
**Is your feature request related to a problem? Please describe.**

@Akshatchaube01 

we can design cookie policy page
when user click on that they will redirected to `/cookie-policy`
it will look like this,

![image](https://github.com/Akshatchaube01/TimeWarp/assets/114583978/b3efa984-8559-465f-a469-2f27c7f5d6d4)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Akshatchaube01** [comment]
We do not plan on adding more pages to the website
