### ISSUE TITLE
[Feat] : Create Beautifully design community page

### ISSUE THREAD

**Issue by dhruv8433** [Akshatchaube01/TimeWarp#270]
**Is your feature request related to a problem? Please describe.**

@Akshatchaube01 
we can beautifully design community page
something like this,

![image](https://github.com/Akshatchaube01/TimeWarp/assets/114583978/e5de0664-968e-4e4b-9765-f37f2511769d)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Akshatchaube01** [comment]
We do not plan on adding more pages to the website
