### ISSUE TITLE
By click on toggle background color it is not working

### ISSUE THREAD

**Issue by kapilG0** [Akshatchaube01/TimeWarp#272]
**Is your feature request related to a problem? Please describe.**
By click on toggle background color it is not working

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

https://github.com/Akshatchaube01/TimeWarp/assets/59639410/a02462aa-22bf-4f05-b3d1-9d21f633fb18

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by kapilG0** [comment]
Hello @Akshatchaube01 please assign this issue to me under gssoc 24

**Comment by Akshatchaube01** [comment]
The landing page doesn't have light and dark mode; the toggle works for all the other pages.
