### ISSUE TITLE
Chatbot not working properly

### ISSUE THREAD

**Issue by MadhurimaNayak** [Akshatchaube01/TimeWarp#277]
**Is your feature request related to a problem? Please describe.**
The chatbot provided on this website is not working properly. There is no response when I ask the chatbot what the project is about.

**Describe the solution you'd like**
Making a custom chatbot that will be able to answer questions related to the project.

**Additional context**
<image src="https://github.com/Akshatchaube01/TimeWarp/assets/124715194/9009801a-a6a3-4ca2-8cc1-046957fb3e5d" height=400px>

**What problem is this feature trying to solve?**
This feature will enhance user experience by making sure a new user is able to understand the project and seek help if they don't.

**How do we know when the feature is complete?**
By conducting robust testing of chatbot, asking it multiple questions that a user could ask and handling special cases. If the chatbot is able to answer, we would know it is functional.

**Comment by MadhurimaNayak** [comment]
@Akshatchaube01 will you add the label when I open a pr?

**Comment by Akshatchaube01** [comment]
Yes
