### ISSUE TITLE
Style Change in our Vision

### ISSUE THREAD

**Issue by maradadivyasree020** [Akshatchaube01/TimeWarp#278]
**Describe the bug**
In mobile mode there is no padding between picture and our vision.

**To Reproduce**

**Expected behavior**
There should be style change it should be like how it is for AboutUs.

**Screenshots**
![Screenshot 2024-06-14 071814](https://github.com/Akshatchaube01/TimeWarp/assets/132190190/6f262178-612d-43b9-82e2-013307a8e648)

**Additional context**

**Comment by Akshatchaube01** [comment]
Not looking for this change right now
