### ISSUE TITLE
Mobile Responsive Design

### ISSUE THREAD

**Issue by Mayur-666** [Akshatchaube01/TimeWarp#28]
**Is your feature request related to a problem? Please describe.**
The website is not responsive for smaller devices like different mobile and tablet screens.

**Describe the solution you'd like**
I will make the whole ui responsive with the help of tailwindcss that is already installed in the project.

What problem is this feature trying to solve?
Responsiveness

### Some screenshots that show lack of responsiveness - 

![Screenshot (519)](https://github.com/Akshatchaube01/TimeWarp/assets/118804110/1298945f-9f33-4e18-bc52-a57f44d46ab7)

![Screenshot (520)](https://github.com/Akshatchaube01/TimeWarp/assets/118804110/6327e964-eadf-46bc-8339-3eb9589fc9c1)

How do we know when the feature is complete?
I'll comment with new design screenshots and make a PR.

**Comment by Mayur-666** [comment]
Please assign me this issue @Akshatchaube01.

**Comment by Akshatchaube01** [comment]
This issue has already been raised

**Comment by Mayur-666** [comment]
ok
