### ISSUE TITLE
Redesign Landing Page

### ISSUE THREAD

**Issue by Mayur-666** [Akshatchaube01/TimeWarp#29]
**Is your feature request related to a problem? Please describe.**
The circles appearing at random position with not so proper geometry is looking weird. 

**Solution :- Adding 3d links to the background, using 2 small packages.

###Current design 

![Screenshot (521)](https://github.com/Akshatchaube01/TimeWarp/assets/118804110/4d7e6ea5-d9df-4ca7-a919-df54cb8994a7)

**Describe the solution you'd like**
I would like to add 3d links in the background of the landing page.

###What i want at background 

These links will be interactive too, i will make them repel if mouse is dragged near them.

![Screenshot (522)](https://github.com/Akshatchaube01/TimeWarp/assets/118804110/54d5c8af-f783-4788-b001-0f4ece563379)

What problem is this feature trying to solve?
Design issue

How do we know when the feature is complete?
Attach ss, and make a PR.

**Comment by Akshatchaube01** [comment]
Sure go ahead !

**Comment by Mayur-666** [comment]
Thanks!

**Comment by Mayur-666** [comment]
@Akshatchaube01  I have added the links, the links will auto adapt to different screens making it responsive, here is the screenshot

![Screenshot (523)](https://github.com/Akshatchaube01/TimeWarp/assets/118804110/9d8a1c8e-7e9b-4a4f-8821-fce4a747f38b)


### Also i want to ask a question, should i create a pull request to merge into main branch or master branch ??

**Comment by Akshatchaube01** [comment]
to the main branch

**Comment by Mayur-666** [comment]
Thanks for merging!
