### ISSUE TITLE
Enhancing the Submit msg 

### ISSUE THREAD

**Issue by Amruta7203** [Akshatchaube01/TimeWarp#295]
**Is your feature request related to a problem? Please describe.**
Enhancing the submit msg on the contact form as it looks very simple 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/Akshatchaube01/TimeWarp/assets/116087736/cfef8653-4a35-46b0-a028-07498e5b2f8e)

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Akshatchaube01** [comment]
Not looking for this change
