### ISSUE TITLE
Beautifying the footer for Demo section 

### ISSUE THREAD

**Issue by Amruta7203** [Akshatchaube01/TimeWarp#298]
**Is your feature request related to a problem? Please describe.**
The current footer is not properly aligned and does not look visually appealing 

**Describe the solution you'd like**
The components inside footer should be placed properly 

![image](https://github.com/Akshatchaube01/TimeWarp/assets/116087736/ec864758-f1f1-4b21-b162-270672ccc9eb)

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Akshatchaube01** [comment]
We are not looking for this change
