### ISSUE TITLE
Misplaced Input in Contact Page

### ISSUE THREAD

**Issue by driyash9881** [Akshatchaube01/TimeWarp#313]
#Misplaced Input in Contact Page
##Before
![image](https://github.com/Akshatchaube01/TimeWarp/assets/118407844/0a7259a7-4911-4cdb-a809-382385b4c8c6)

##After
![image](https://github.com/Akshatchaube01/TimeWarp/assets/118407844/335ee957-ef66-4192-89eb-ac068f9828ff)

**Comment by Akshatchaube01** [comment]
This issue has already been taken
