### ISSUE TITLE
Add Licensing Page Reflecting MIT License to Website Footer

### ISSUE THREAD

**Issue by MastanSayyad** [Akshatchaube01/TimeWarp#315]
Hey @Akshatchaube01 

**Is your feature request related to a problem? Please describe.**

The website currently does not have a dedicated Licensing page. To ensure that users are aware of the licensing terms, it is essential to add a Licensing page that reflects the MIT license and link it in the website's footer.

![image](https://github.com/Akshatchaube01/TimeWarp/assets/101971980/05e01434-a3ae-4219-b644-4b2cc19ccc95)

![image](https://github.com/Akshatchaube01/TimeWarp/assets/101971980/db394f4c-71d2-47c7-a684-54a5dd27cdb4)

**Describe the solution you'd like**

- Create a new React component for the Licensing page using react styled components
- Add the MIT license text to this component.
- Update the website's footer to include a link to the new Licensing page.

**Describe alternatives you've considered**

N/A

**Comment by Akshatchaube01** [comment]
https://github.com/Akshatchaube01/TimeWarp/blob/main/LICENSE
l
