### ISSUE TITLE
Add a Rate Us Option 

### ISSUE THREAD

**Issue by sailaja-adapa** [Akshatchaube01/TimeWarp#317]
Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 

Can you please assign me this issue under gssoc'24

**Comment by Akshatchaube01** [comment]
Where do you plan on adding this feature ?

**Comment by sailaja-adapa** [comment]
@Akshatchaube01 I would like to add rate us option on navbar and I will add 5 starts and feedback box under it in an attractive way and a submit button

**Comment by sailaja-adapa** [comment]
@Akshatchaube01 can you assign me this issue under GSSOC'24

**Comment by Akshatchaube01** [comment]
We are not looking for this feature right now
