### ISSUE TITLE
Contributor List Animation Bug and UI Improvement Request

### ISSUE THREAD

**Issue by yogirajbshinde21** [Akshatchaube01/TimeWarp#340]
### **Bug :**
The contributor list animation restarts before completing its full cycle.

---
### **To Reproduce :**
Go to 'About Us' page.
Scroll to 'Contributors' section.
Observe the animation restarting early.

---
### **Expected behavior :**
The animation should smoothly scroll through all contributors before restarting.

---
### **Screenshots**
![Screenshot 2024-06-27 141937](https://github.com/Akshatchaube01/TimeWarp/assets/84953719/4a9526a5-a56e-4449-b0f4-5bc803fbff48)

---
### **Additional context**
The animation duration may not be synchronized with the content length. Adjusting the duration dynamically might resolve this issue.

---
Can you please assign this issue to me? @Akshatchaube01 
Additionally, the UI of the cards doesn't look very appealing. May I work on improving it as well?

**Comment by Akshatchaube01** [comment]
You can work on the bug, let the UI stay the same for now . All the best !
