### ISSUE TITLE
To fix the alignment as well as the UI in footer section.

### ISSUE THREAD

**Issue by yogirajbshinde21** [Akshatchaube01/TimeWarp#345]
**Describe the bug**
A footer is unproperly aligned. it badly impacts website's impression. Also, adding a transparent layer on the footer would make it look better for UI.

**Screenshots**
![Screenshot 2024-06-29 004053](https://github.com/Akshatchaube01/TimeWarp/assets/84953719/f5da7085-b027-47d7-92f0-e6554b07f935)
@Akshatchaube01

**Comment by Akshatchaube01** [comment]
This issue is already being worked on right now in issue no #342
