### ISSUE TITLE
Add Reset Functionality and Thank You pop up Message After Subscribing Also Change the Color Grading

### ISSUE THREAD

**Issue by MastanSayyad** [Akshatchaube01/TimeWarp#372]
Hey @Akshatchaube01 

The newsletter subscribe section in footer is empty like after clicking on the subscribe button the email input does not resets nor it indicates that the user has subscribed 

- I would like to add a Reset functionality after subscribing so that the input gets resets for other submission
- Add Thank You Pop up Message to indicate the user has successfully subscribed to the TimeWarp Newsletter 
- Additionally, the color to the placeholder and input blends the text causing readability issues!

![image](https://github.com/user-attachments/assets/dfadf977-f68e-4660-9518-b75e11635f22)

https://github.com/user-attachments/assets/ed0519d9-c350-4f61-93b0-1f4797a6ffdf

Could you please assign this issue to me?

**Comment by Akshatchaube01** [comment]
Please pull the recent changes
