### ISSUE TITLE
Title: Adding Discord and facebook accounts in footer at follows section

### ISSUE THREAD

**Issue by GAVINESHWAR** [Akshatchaube01/TimeWarp#375]
**Is your feature request related to a problem? Please describe.**

In the footer section there are only 4 social media icons and I would like to add the facebook and discord accounts icons to make better reach in the tech industry. In the contact us page twitter icon is added wrong assign me  to remove the old icon and add new Icon.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/user-attachments/assets/60738a01-b47f-4c9a-b932-98232ad0b790)
here Facebook and Discord icons can be added.

![image](https://github.com/user-attachments/assets/e20d7ff5-9e1a-40f9-878c-8c288eddac64)
Here old twitter icon is there , it should be removed.

@Akshatchaube01 , assign me this issue to make contribution to the project.

**Comment by Akshatchaube01** [comment]
Not looking for this right now
