### ISSUE TITLE
Add Cards alignments to Contributors section instead of slideshow to Improve UX

### ISSUE THREAD

**Issue by MastanSayyad** [Akshatchaube01/TimeWarp#378]
Hey @Akshatchaube01 

I suggest adding cards only instead of slideshow to the our contributors section in about us page
as the slideshow never stops even when hover, making it Is difficult to see the list also it reduce the  user experience

https://github.com/user-attachments/assets/a4be7f40-c36f-4ea4-924c-99a5d2f4e3d7

I would like to remove it and add cards only with proper alignments and perfectly responsive!

### **Like this:**

![image](https://github.com/user-attachments/assets/ba326bec-a7ca-4f85-b750-e46b28b19f35)

![image](https://github.com/user-attachments/assets/c7f6b572-a587-4491-b795-812432d60c18)

https://github.com/user-attachments/assets/221f5759-c11f-40b1-b4a6-e0fca1a6c9e7

**Comment by Akshatchaube01** [comment]
We are not looking for this right now
