### ISSUE TITLE
Adding more social media icons and the alignment

### ISSUE THREAD

**Issue by jayanththalla** [Akshatchaube01/TimeWarp#383]
**Is your feature request related to a problem? Please describe.**
There is no other social media icons like discord and linkedin

**Describe the solution you'd like**
Adding more social media icons in the footer
**Describe alternatives you've considered**

**Additional context**
please assign me @Pa
What problem is this feature trying to solve?

How do we know when the feature is complete?

**Comment by Akshatchaube01** [comment]
We are not looking for this right now
