### ISSUE TITLE
Homepage Footer Not Visible

### ISSUE THREAD

**Issue by lovelymahor** [Akshatchaube01/TimeWarp#394]
**Is your feature request related to a problem? Please describe.**
The footer section on the homepage is currently not visible. This is impacting the overall layout and user experience of the website as important information and links in the footer are inaccessible.

**Describe the solution you'd like**
The footer should be visible at the bottom of the homepage, consistently across different devices and screen sizes. It should contain the necessary links, copyright information, and any other relevant content as specified in the design. The footer should be styled appropriately to match the website's overall design and be easily accessible to users.

**Describe alternatives you've considered**

**Alternatives -**
Fixed Footer- Making the footer fixed at the bottom of the viewport so that it's always visible regardless of the page content length.
Sticky Footer- Implementing a sticky footer that remains at the bottom unless the page content pushes it further down.

**Additional context**
Context-
The current issue is that the footer is either not rendering correctly or is being hidden due to CSS or HTML structure issues.
Users have reported not being able to see the footer, which affects navigation and accessibility.

What problem is this feature trying to solve?
This feature aims to ensure the footer is always visible, improving user navigation and accessibility. A visible footer is essential for providing users with quick access to important links and information, such as contact details, privacy policies, and social media links.

How do we know when the feature is complete?
The footer is visible at the bottom of the homepage across all devices and screen sizes.
The footer contains all required links and information as per the design specifications.
The footer's styling is consistent with the website's overall design.
No overlapping or visibility issues are present, even with varying content lengths on the page.
User testing confirms that the footer is easily accessible and functional.

![Screenshot (263)](https://github.com/user-attachments/assets/58593b00-151f-4974-9347-30c7115b681e)

**Comment by lovelymahor** [comment]
@Akshatchaube01 Please assign it to me I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

**Comment by Akshatchaube01** [comment]
We are not looking for this change right now
