### ISSUE TITLE
Rework of the Contact Us Page

### ISSUE THREAD

**Issue by KrishKoria** [Akshatchaube01/TimeWarp#43]
**Is your feature request related to a problem? Please describe.**
The current contact us sections very bland and boring and also doesn't match with the Theme of the website

**Describe the solution you'd like**
I want to Rework the entire contact us page, add some better styling as well some better input validations

**I would Like to assigned this issue under GSSOC'24**

**Comment by Akshatchaube01** [comment]
The contact us page is already being worked upon in issue #24
