### ISSUE TITLE
[Feat]:want to add functionality to send email to the owner when user submit the contact us from

### ISSUE THREAD

**Issue by AnitSarkar123** [Akshatchaube01/TimeWarp#57]
**Is your feature request related to a problem? Please describe.**
send email to the owner mail when user submit the contact us from

**Describe the solution you'd like**
I am going to use email.js

**Comment by Akshatchaube01** [comment]
@AnitSarkar123 Are you working on this issue ?

**Comment by AnitSarkar123** [comment]
Yes sir @Akshatchaube01 email.js is showing some issue

**Comment by Akshatchaube01** [comment]
Okay, keep working on it.. do pull the latest code before you make a PR
