### ISSUE TITLE
Making the links in the Demo section for the References more Highlighted and Visible

### ISSUE THREAD

**Issue by AnupamSingh2004** [Akshatchaube01/TimeWarp#61]
**The links for the references in the Demo section** 
- All the links which are provided at the bottom of the Demo section page of the website do not appear to be clickable and much highlighted as shown

![Screenshot from 2024-05-14 11-49-48](https://github.com/Akshatchaube01/TimeWarp/assets/107802976/cce5120d-31d5-45a7-8865-2c7e6028c0aa)

**Solution**
- I would like to make the Resources section and text bold and arranged in a proper manner with pop out animation along with icons or logos attached to them for their respective fields 

Please assign this issue to me

**Comment by AnupamSingh2004** [comment]
I would like to work on this issue, please assign this issue to me under GSSOC contibuter

**Comment by aryapandeyy22** [comment]
I would like to work on this please assign me this under gssoc'24
