### ISSUE TITLE
[FEATURE]: Create a Specific Models Page / Template 

### ISSUE THREAD

**Issue by yashmandi** [Akshatchaube01/TimeWarp#69]
In the 'Models' Page, there are various models, and I believe each model has its own information, features, etc. So I think it would be great to create a seperate page to each specific model. 

The current 'Model' Page will remain same, my idea is to just create a sort-of template, which you guys can use in future to update / add the new model. When the user clicks on any of the model, he will get routed to that specific model he has clicked on to, where the user will find more details about that particular model.

This feature resolves the problem of the users wandering about the model. If the user can get to know about the model right after clicking on the specific model, it's a good thing, and the user will explore more models as well.

I would like to contribute to this task. Request you to assign this task to me under GSSoC '24 ;)

_Here's the page I'm talking about_
![Screenshot (203)](https://github.com/Akshatchaube01/TimeWarp/assets/132436131/df7dc3c4-8fbb-4136-aa28-f21d7d987256)

**Comment by Akshatchaube01** [comment]
Not looking for this feature right now, thankyou for raising an issue !
