### ISSUE TITLE
Improve Homepage with 3D Background

### ISSUE THREAD

**Issue by Akshatchaube01** [Akshatchaube01/TimeWarp#7]
Background:
The homepage lacks visual appeal and needs enhancement.

Proposal:
Add a 3D background to elevate aesthetics and engagement.

Suggested Implementation:
1) Design Concept: Work with a designer to create a visually captivating 3D rendering.
2) Integration: Seamlessly integrate the 3D rendering into the homepage layout.
3) Performance Optimization: Optimize file size and loading speed (optional ).

Expected Benefits:
1) Enhanced Visual Appeal: A 3D background adds depth and realism.
2) Improved Engagement: Captivate users' attention.
3) Brand Enhancement: Reinforce brand identity.

**Comment by Harshu467** [comment]
I want to work on this issue , please assign this to me

**Comment by IshaanMinocha** [comment]
i would like to work on this and make an interactive 3d particle ring effect in the background using fm3d library and 3js

**Comment by r7projects-shayan** [comment]
@Akshatchaube01 I would like to introduce beautiful 3d particle collision effect for the homepage and add some more things to it so that it is more visually appealing to the users. Kindly assign it to me

**Comment by Akshatchaube01** [comment]
Raise a new issue for background of other pages - Contact us, models, About us. This one has already been assigned. @r7projects-shayan

**Comment by IshaanMinocha** [comment]
this has been done and i have sent a pull request. 
pls close this issue after merging @Akshatchaube01
