### ISSUE TITLE
About Section Background Issue.

### ISSUE THREAD

**Issue by Mayur-666** [Akshatchaube01/TimeWarp#76]
**Is your feature request related to a problem? Please describe.**
The background lines of about us page are shadowing the content.

**Describe the solution you'd like**
The no. of lines should be reduced and the movement should be made a little slower, so that they can appear subtle and nice with 
the environment.

**Comment by Mayur-666** [comment]
@Akshatchaube01  Please assign me so that i can work on it and show the screenshots.

**Comment by Mayur-666** [comment]
@Akshatchaube01  Tell me any suggestion you like (otherwise tell me I'll create PR):- 
 - The lines are now at background with smaller z index
 - The movement speed is reduced which make them soothing
 - Opacity and color have been reduced a little so as to make content more important.
 - Now the lines are not shadowing the content.

![Screenshot (553)](https://github.com/Akshatchaube01/TimeWarp/assets/118804110/1969a220-f457-4631-94e5-8c2a12ecb70d)

**Comment by Akshatchaube01** [comment]
You can make a PR
