### ISSUE TITLE
Enhancement: Landing Page Alignment

### ISSUE THREAD

**Issue by Ani1702** [Akshatchaube01/TimeWarp#78]
The TimeStamp div is not aligned at the centre. 

![image](https://github.com/Akshatchaube01/TimeWarp/assets/64695047/3195316e-118d-4005-8a74-a2a3b3b7a5ee)

**Comment by Ani1702** [comment]
[Akshatchaube01](https://github.com/Akshatchaube01), Kindly assign it to me under GSSOC'24.

**Comment by yashika0432** [comment]
Hey, can this issue be assigned to me under gssoc i have been looking forward to contributing to something and this looks like one of the things i would be interested in

**Comment by Rv43** [comment]
hey, can you assign this issue to me. I am intersted in to solve this issue

**Comment by Akshatchaube01** [comment]
The issue has been solved
