### ISSUE TITLE
Resource Links

### ISSUE THREAD

**Issue by Ani1702** [Akshatchaube01/TimeWarp#79]
**Describe the bug**
API Reference link redirects to google.com

**To Reproduce**
1. Go to Demo Section
2. Click on API Reference
3. See error

**Expected behavior**
It should redirect to the actual API reference.

**Screenshots**
![image](https://github.com/Akshatchaube01/TimeWarp/assets/64695047/18111cf4-ac2b-4434-9be6-17145379103f)

**Additional context**
Kindly provide the link to the actual reference of the API. 

@Akshatchaube01, I request you to assign me this issue under GSSoC'24.

**Comment by Ani1702** [comment]
Kindly provide the resource link for API reference to be attached.

**Comment by Akshatchaube01** [comment]
I am going to change this section soon, so there is no need for it.
