### ISSUE TITLE
[UI EHHANCEMENT]: Implement theming using shadcn ui

### ISSUE THREAD

**Issue by rohansen856** [Akshatchaube01/TimeWarp#82]
**Is your feature request related to a problem? Please describe.**
The overall theme of the app is too random. The best solution would be using a fixed theme for the entire site.

**Describe the solution you'd like**
I would like to fix the site's look by implementing `shadcn-ui`, one of the best UI theming libraries for this purpose.

**Additional context**
Please assign me this issue under GSSOC'24

**Comment by Akshatchaube01** [comment]
Not looking for this right now. Thankyou for raising an issue.
