### ISSUE TITLE
Responsive error on the Demo Section Page

### ISSUE THREAD

**Issue by shubhammjha22** [Akshatchaube01/TimeWarp#85]
**Describe the bug**
There is poor responsiveness in the demo section page

![image](https://github.com/Akshatchaube01/TimeWarp/assets/68507333/2babe5e8-1597-428c-833c-4e7706d21d2e)

**To Reproduce**
1. Go to Demo Section Page
2. Reduce the screen size to below 1200px
3. Scroll down a bit to the Technology Used Section
4. You could see there is a poor responsive of these card 

**Expected behavior**
The Card should be made properly responsive as they are in Screen below 740px

![image](https://github.com/Akshatchaube01/TimeWarp/assets/68507333/44bbf666-6460-4118-a8e2-f3bcad7277b9)

Please assign this issue to me , as i would like to work on it under gssoc.

**Comment by shubhammjha22** [comment]
@Akshatchaube01  Can you please assign this issue to me , i would like to work on this.

**Comment by shubhammjha22** [comment]
@Akshatchaube01 It's been 2 days , you havent assign or are u planning to solve it by yourself , please clarify !

**Comment by Akshatchaube01** [comment]
This issue was taken up by someone but they didn't fix the problem completely, so I am assigning it to you

**Comment by shubhammjha22** [comment]
Hey @Akshatchaube01  , i would like to ask you can we increase the overall size of technology card -

Currently - it is this-
![image](https://github.com/Akshatchaube01/TimeWarp/assets/68507333/dab55103-89f4-45b8-9227-54c28ad835f2)


and I'm thinking of make it to this - 
![image](https://github.com/Akshatchaube01/TimeWarp/assets/68507333/5e70beba-0044-4438-92c9-c1eb154d59e6)

Or do you suggest we stick to the Current size ? 

Ps- responsiveness is almost fixed.

**Comment by Akshatchaube01** [comment]
You can implement the second one, it looks good @shubhammjha22

**Comment by shubhammjha22** [comment]
@Akshatchaube01 i have made the PR , i would request you to add the apt labels.
Thank You

**Comment by shubhammjha22** [comment]
@Akshatchaube01  Please add the apt label and tags  in the [Issue](https://github.com/Akshatchaube01/TimeWarp/issues/85) as well as in the [PR](https://github.com/Akshatchaube01/TimeWarp/pull/91)

![image](https://github.com/Akshatchaube01/TimeWarp/assets/68507333/0d1ae9e3-a076-4706-9eef-22b2db873d5b)
