### ISSUE TITLE
Improvising the Contact Us page

### ISSUE THREAD

**Issue by MetiUmashri** [Akshatchaube01/TimeWarp#88]
The Contact Us page in the w.r.t mobile UI is quite basic and overlapping. Would like to make it more interactive. Will also try to improvise the footer section of this page.

![image](https://github.com/Akshatchaube01/TimeWarp/assets/97387069/c47c27b3-7470-4564-a1de-833bda9a1e82)

Kindly assign this issue to me would really like to improvise this feature.

**Comment by Akshatchaube01** [comment]
The issue has been fixed
