### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by teamharsh** [Akshatchaube01/TimeWarp#9]
You can assign me to create a custom favicon for your web page according to your requirements.

**Comment by Akshatchaube01** [comment]
@AMISH-KHAN you can start working on it

**Comment by AMISH-KHAN** [comment]
hi @Akshatchaube01 need some suggestion here
1:
![favicon-16x16](https://github.com/Akshatchaube01/TimeWarp/assets/123164129/be9d3cc5-16fc-4449-b482-ba3d69f1f73c)

for this one I decided to go with the cartoon we have at about us. It just looks cool.


2:
![icon_VR](https://github.com/Akshatchaube01/TimeWarp/assets/123164129/df28a795-6249-4638-9ee8-d54c66260ef3)

the 2nd one is in png form I will convert it into favicon if you approve.

so what are your thoughts?

**Comment by Akshatchaube01** [comment]
2nd one is fine

**Comment by AMISH-KHAN** [comment]
@Akshatchaube01  please review pr #100
